[package]
name = "frontend"
edition.workspace = true
version.workspace = true

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
console_error_panic_hook = "0.1"
gloo-net = { version = "0.6", features = ["http"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
  "AbortController",
  "AbortSignal",
  "Window",
  "Location",
  "Navigator",
  "Clipboard",
  "Document",
  "DomRect",
  "Element",
  "HtmlElement",
  "Storage",
  "MediaQueryList",
  "Event",
  "EventTarget",
  "KeyboardEvent",
  "Node",
] }
serde = { workspace = true }
shared = { path = "../shared" }
